Second
Epifantsev/sql-final pull request #1
Opened 2024-09-02 14:15 UTC by Epifantsev

2024-09-02 16:05 UTC, dirtymew requested changes
Павел

очень хорошая работа - но все же есть что поправить

2024-09-02 16:05 UTC, dirtymew commented on main.go
> +
лишняя строка )

2024-09-02 16:05 UTC, dirtymew commented on parcel.go
> +		fmt.Println(err)
тут лишнее логирование  -ошибки печатаются в main

2024-09-02 16:05 UTC, dirtymew commented on parcel.go
> +	row := s.db.QueryRow("SELECT * FROM parcel WHERE number = :number",
лучше явно указывать поля

2024-09-02 16:05 UTC, dirtymew commented on parcel.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-09-02 16:05 UTC, dirtymew commented on parcel.go
> +	row := s.db.QueryRow("SELECT status FROM parcel WHERE number = :number",
тут плохое решение - все можно сделать одним запросом UPDATE

2024-09-02 16:05 UTC, dirtymew commented on parcel.go
> +	row := s.db.QueryRow("SELECT status FROM parcel WHERE number = :number",
тоже самое что и в SetAddress

2024-09-02 16:05 UTC, dirtymew commented on parcel_test.go
> +	p, err := store.Get(int(res))
лишнее приведение типов в int(res)

2024-09-02 16:05 UTC, dirtymew commented on parcel_test.go
> +	assert.Empty(t, p)
еще хорошо бы ошибку проверить assert.ErrorIs

2024-09-02 16:05 UTC, dirtymew commented on parcel_test.go
> +	assert.Equal(t, len(storedParcels), len(parcels))
assert.Len

2024-09-02 17:13 UTC, Epifantsev commented
Большое спасибо за ревью !

2024-09-03 12:40 UTC, dirtymew approved these changes
Павел

все ок 

зачет

2024-12-10 16:31 UTC, merged